FROM python:3.12-slim-bookworm

WORKDIR /app

COPY ./src /app
COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 8000

CMD [ "" ]